import json
import pytest
from pathlib import Path

@pytest.mark.asyncio
async def test_scraper_json_sample_exists():
    path = Path("samples/scraped.json")
    assert path.exists(), "scraped.json file should be generated by scraper"

    with open(path) as f:
        data = json.load(f)

    assert isinstance(data, list)
    assert "title" in data[0]  # check expected field
